### ISSUE TITLE
Sprint 2 Review

### ISSUE THREAD

**Issue by katherine-van-der-ploeg** [thestormtroopers/web-app#11]
Ultimately, we were successful in getting everything done. This past week we identified the user base, decided on what we wanted and didn't want for our application based on what we observed from top competing web applications, and began a wireframe that features these wants.

**Comment by katherine-van-der-ploeg** [comment]
@thomasjbradley

**Comment by katherine-van-der-ploeg** [comment]
Reflection: It's a little weird working within the github project page but I'll consider that a lack of practice, once I  get used to remembering to use it I don't think that'll be an issue. I ended up working on parts of my tasks in class but ultimately they got finished. I feel like they serve their purpose but otherwise are a tad lacklustre due to the ambiguity of weather applications (it is a little difficult to pin down exact functionality due to their connection to news pages, other websites, etc.)

**Comment by emnemdesign** [comment]
Reflection: This past week up til now I have been working on the personas and I think I did well for what I could come up with based off of challenges I have heard from people along the way.

**Comment by thomasjbradley** [comment]
Where is the reflection from @taylorion ?

---

The Sprint 2 Issues look great—I see you tried to use todo list but they didn’t render properly. The syntax is like this:

```md
- [ ] Thing
```

*Dash space bracket space bracket space text…*

Looking at the Sprint 2 Project board most of the tasks are still in review and the sprint is incomplete.

**Comment by taylorion** [comment]
@thomasjbradley 
**REFLECTION**
This past week was pretty difficult for me because of family reasons. I'm getting used to working in github and the collaboration, so I think that will still take some time but as the project progresses, I am confident that I will get used to it. 

I completed basic interactive wire-framing and began iconography sets for the project for this week, and will continue to work on the icons and revise / edit the wireframes as per group discussions.
